### ISSUE TITLE
Reschedule future tournaments on startup

### ISSUE THREAD

**Issue by cthill** [cthill/realtime-tournament#51]

**Comment by cthill** [comment]
Working: 4f7f93e4a8462c1d600b19458168fcd988191334
@bmzhao do you mind looking at this? Seemed like the easiest way to accomplish rescheduling.

**Comment by cthill** [comment]
I'm not sure how the ask() timeouts work when an actor is asking itself. Could there be a timeout issue if there are too many tournamentRuns to reschedule?

**Comment by bmzhao** [comment]
According to http://doc.akka.io/docs/akka/current/java/actors.html, `ask` works by creating an internal actor to handle the reply. And I think that internal actor also handles the execution of callbacks from the Future object, since the docs warn about having callbacks close over the original actor's mutable state, causing concurrent access to shared memory (the opposite of the actor pattern). This means that `ask`ing the self actor shouldn't cause a deadlock, (contrary to what this StackOverflow answer says https://stackoverflow.com/a/22320863/6373623). 

However, I don't like having an actor `ask` itself (usually you use `tell` if you're sending a message to self), since you're subjecting yourself to a timeout when you can instead control your own execution pace. So, yes, I agree there could be a timeout issue if there's a ton of tournamentRuns to schedule at the beginning. Plus, we need a guarantee that all scheduling initialization occurs before receiving any messages from external sources (which isn't the case here since messages are asynchronously delivered). 

I'd refactor the guts of the `scheduleNewTournamentActor` method to a helper method that returns an Either<Success,Failure> object, and have the `processIncompleteTournamentRuns` method directly call that helper. This way, we guarantee the master actor is in a correct state before receiving any other messages since we synchronously execute the scheduling tasks in the constructor. Also, the new `scheduleNewTournamentActor` can just call the helper method, and `tell` the sender the result of helper.

**Comment by cthill** [comment]
Done: d4f4d0993017343898491f2953ba9db6cf3fcb6f
